// This file is generated by npm run build:icons

export type IconName =
	| "arrowUpRight"
	| "brand"
	| "check"
	| "chevronDown"
	| "clipboard"
	| "copy"
	| "dark"
	| "discord"
	| "discourse"
	| "doubleChevronRight"
	| "download"
	| "github"
	| "light"
	| "star"
	| "system"
	| "x"
	| "youtube";
