// This file is generated by npm run build:icons

export type IconName =
	| "arrowUpRight"
	| "check"
	| "chevronDown"
	| "clipboard"
	| "discord"
	| "discourse"
	| "doubleChevronRight"
	| "github"
	| "x"
	| "youtube";
