/* eslint-disable prettier/prettier */
export const Constants = Object.freeze({
  ALL_CONTRIBUTORS: 'https://github.com/redwoodjs/redwood#all-contributors',
  BIGHORN_FEATURES: '/blog/rsc-now-in-redwoodjs',
  CODE_OF_CONDUCT: 'https://github.com/redwoodjs/redwood/blob/main/CODE_OF_CONDUCT.md',
  COMMUNITY: 'https://community.redwoodjs.com/t/welcome-to-the-redwoodjs-community/2416',
  CONFERENCE: 'https://redwoodjsconf.com/',
  CONTRIBUTORS_MEETUP: 'https://community.redwoodjs.com/t/contributors-meetups-a-next-step-for-redwoodjs-participation/2470',
  CONTRIBUTING: 'https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md',
  CORE_TEAM: 'https://github.com/redwoodjs/redwood#core-team-leadership',
  CREATE_REDWOOD_SCRIPT: 'yarn create redwood-app',
  DISCORD: 'https://discord.com/invite/redwoodjs',
  DISCOURSE: 'https://community.redwoodjs.com/',
  DOCS: 'https://docs.redwoodjs.com/docs/introduction',
  EMAIL: '',
  EVENTS: 'https://lu.ma/redwoodjs',
  GET_STARTED: 'https://redwoodjs.com/docs/quick-start',
  GITHUB: 'https://github.com/redwoodjs/redwood',
  GITHUB_STARS: '16.9k',
  GITHUB_RELEASE: 'https://github.com/redwoodjs/redwood/releases',
  MAKER_HOUR: 'https://community.redwoodjs.com/t/redwood-makers-hour-stand-up/1971',
  NEWSLETTER: 'https://mailchi.mp/redwoodjs/redwoodjs-newsletter',
  PRESTON_WERNER_VENTURES: 'https://prestonwernerventures.com/',
  README: 'https://github.com/redwoodjs/redwood/blob/main/README.md',
  RELEASES: 'https://community.redwoodjs.com/c/announcements/releases-and-upgrade-guides/18',
  SECURITY: 'https://github.com/redwoodjs/redwood/security/policy',
  SHOP: 'https://shop.redwoodjs.com/',
  STARTUP_CLUB: 'https://docs.google.com/forms/d/e/1FAIpQLSeuoGpGJ8gN_eYRY9hU6u2Apw0RB5UV6eYASp6ujsSv_aLaMg/viewform',
  STARTUP_FUND: 'http://redwoodstartupfund.com/',
  TUTORIAL: 'https://redwoodjs.com/docs/tutorial/foreword',
  VERSION: 'v7.7',
  X: 'https://twitter.com/redwoodjs',
  YOUTUBE: 'https://www.youtube.com/redwoodjs',
  YOUTUBE_SERIES: 'https://www.youtube.com/watch?v=Xr92RcUMngc&list=PLrz61zkUHJJFzXe0xZ55RdAF3o3PGhd0U'
})
